Rating draft
stsrki/Blazorise pull request #2017
Opened 2021-03-11 20:25 UTC by andreatosato

Rating work only with Fontawesome because Star (full) and (empty) has same class name but difference is "regular" or "solid" icon style.

I want to color Icon but not work preperly

2021-03-12 20:33 UTC, andreatosato commented
I add some feature and demo for Material Icon.

I need to develop:
1. Color icon
2. Disabled component

@stsrki  Can you help me in this 2 feature?
Can you review code and suggest me?
Thanks a lot

2021-03-13 21:47 UTC, stsrki commented
Hi @andreatosato, I made some more changes so please test it.

I also plan to adjust colors to be applied from theme settings.

For Color and Size I still need to decide if it makes sense to add it now or postpone that feature for some other time.

2021-03-14 08:42 UTC, andreatosato commented
Color is very hardcoded feature. But for now I think that coverage many use cases.
I fix material sample and test each platform (Bootstrap and Material).
Can you merge this feature?

2021-03-14 09:40 UTC, stsrki commented
I will need to write documentation before I merge. And will try to add validation support. It might come in handy.

2021-03-14 09:42 UTC, andreatosato commented
Can I help you?
Is there guideline?

2021-03-14 09:45 UTC, stsrki commented
You mean with documentation? If you want you can write it under `docs/_docs/components` path. Just create a new md file. Look for other files as an example. Once you Submit I will review. Thanks

2021-03-14 15:47 UTC, andreatosato commented
I add draft docs.

2021-03-14 15:51 UTC, stsrki requested changes

2021-03-14 15:51 UTC, stsrki commented on docs/_docs/components/rating.md
> +## Basic Memo
There are still some descriptions for memo component. Can you fix it?

2021-03-18 13:32 UTC, stsrki commented
I think the PR is now ready to be merged. @andreatosato can you test it once last time, please?

2021-03-23 15:45 UTC, merged